version: '3'
services:
  keymanager-rest:
    image: 'matheuscarv69/orange-talents-05-template-pix-keymanager-rest'
    container_name: "keymanager-rest"
    environment:
      KEY_MANAGER_HOST: keymanager-grpc
      KEY_MANAGER_PORT: 50051
    ports:
      - 8080:8080
    depends_on:
      - keymanager-grpc

  keymanager-grpc:
    image: 'matheuscarv69/orange-talents-05-template-pix-keymanager-grpc'
    container_name: "keymanager-grpc"
    environment:
      POSTGRES_HOST: postgres:5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
      ITAU_URL: http://erp-itau:9091
      BCB_URL: http://bcb:8082
    ports:
      - 50051:50051
    depends_on:
      - postgres

  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091
  postgres:
    image: 'postgres:alpine'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'